const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGR: "CHANGE_LANGUAGR",

  //user
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  //admin
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAIL: "FETCH_GENDER_FAIL",

  //doctor
  FETCH_DOCTOR_SUCCESS: "FETCH_DOCTOR_SUCCESS",
  FETCH_DOCTOR_FAIL: "FETCH_DOCTOR_FAIL",
  //alldoctor
  FETCH_ALLDOCTOR_SUCCESS: "FETCH_ALLDOCTOR_SUCCESS",
  FETCH_ALLDOCTOR_FAIL: "FETCH_ALLDOCTOR_FAIL",

  //savedetaildoctor
  FETCH_SAVEDETAI_DOCTOR_SUCCESS: "FETCH_SAVEDETAI_DOCTOR_SUCCESS",
  FETCH_SAVEDETAI_DOCTOR_FAIL: "FETCH_SAVEDETAI_DOCTOR_FAIL",

  //detaildoctor
  FETCH_DETAIL_DOCTOR_SUCCESS: "FETCH_DETAIL_DOCTOR_SUCCESS",
  FETCH_DETAIL_DOCTOR_FAIL: "FETCH_DETAIL_DOCTOR_FAIL",
});

export default actionTypes;
