const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGR: "CHANGE_LANGUAGR",

  //user
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  //admin
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAIL: "FETCH_GENDER_FAIL",

  //doctor
  FETCH_DOCTOR_SUCCESS: "FETCH_DOCTOR_SUCCESS",
  FETCH_DOCTOR_FAIL: "FETCH_DOCTOR_FAIL",
  //alldoctor
  FETCH_ALLDOCTOR_SUCCESS: "FETCH_ALLDOCTOR_SUCCESS",
  FETCH_ALLDOCTOR_FAIL: "FETCH_ALLDOCTOR_FAIL",

  //savedetaildoctor
  FETCH_SAVEDETAI_DOCTOR_SUCCESS: "FETCH_SAVEDETAI_DOCTOR_SUCCESS",
  FETCH_SAVEDETAI_DOCTOR_FAIL: "FETCH_SAVEDETAI_DOCTOR_FAIL",

  //detaildoctor
  FETCH_DETAIL_DOCTOR_SUCCESS: "FETCH_DETAIL_DOCTOR_SUCCESS",
  FETCH_DETAIL_DOCTOR_FAIL: "FETCH_DETAIL_DOCTOR_FAIL",

  //AllCODE_SCHEDULE
  FETCH_DETAIL_AllCODE_SCHEDULE_SUCCESS:
    "FETCH_DETAIL_AllCODE_SCHEDULE_SUCCESS",
  FETCH_DETAIL_AllCODE_SCHEDULE_FAIL: "FETCH_DETAIL_AllCODE_SCHEDULE_FAIL",

  //Required_Doctor
  FETCH_DETAIL_Required_Doctor_Info_SUCCESS:
    "FETCH_DETAIL_Required_Doctor_Info_SUCCESS",
  FETCH_DETAIL_Required_Doctor_Info_FAIL:
    "FETCH_DETAIL_Required_Doctor_Info_FAIL",

  //Required_Doctor
  FETCH_DETAIL_Create_booking_Info_SUCCESS:
    "FETCH_DETAIL_Create_booking_Info_SUCCESS",
  FETCH_DETAIL_Create_booking_Info_FAIL:
    "FETCH_DETAIL_Create_booking_Info_FAIL",

  //verifyCreateBooking
  FETCH_DETAIL_verifyCreateBooking_SUCCESS:
    "FETCH_DETAIL_verifyCreateBooking_SUCCESS",
  FETCH_DETAIL_verifyCreateBooking_FAIL:
    "FETCH_DETAIL_verifyCreateBooking_FAIL",

  //ListBooking
  FETCH_ListBooking_SUCCESS: "FETCH_ListBooking_SUCCESS",
  FETCH_ListBooking_FAIL: "FETCH_ListBooking_FAIL",
});

export default actionTypes;
